# Import

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
import json
import os
from tensorflow.keras import layers, models

# Read CSV

In [ ]:
# Specify the path to the CSV file
file_path = 'jabodetabek_house_data_prcsd.csv'

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(file_path)

# Print the Dataframe
df

,url,price_in_rp,title,address,district,city,lat,long,facilities,property_type,...,fac_canopy,fac_smart_home,fac_backyard_luas,fac_garasi,fac_balkon,fac_basement,fac_gudang,fac_clubhouse,fac_service_area,fac_plumbing_system
0,https://www.rumah123.com/properti/bekasi/hos11...,2.990000e+09,"rumah cantik sumarecon bekasi lingkungan asri,...","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"['Tempat Jemuran', 'Jalur Telepon', 'Taman', '...",rumah,...,0,0,0,0,0,0,0,0,0,0
1,https://www.rumah123.com/properti/bekasi/hos10...,1.270000e+09,"rumah kekinian, magenta summarecon bekasi","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,['Taman'],rumah,...,0,0,0,0,0,0,0,0,0,0
2,https://www.rumah123.com/properti/bekasi/hos10...,1.950000e+09,rumah cantik 2 lantai cluster bluebell summare...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"[' Jogging Track', ' Kolam Renang', 'Masjid', ...",rumah,...,0,0,0,0,0,0,0,0,0,0
3,https://www.rumah123.com/properti/bekasi/hos10...,3.300000e+09,rumah mewah 2lantai l10x18 c di cluster vernon...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"[' Jalur Telepon', ' Jogging Track', 'Track La...",rumah,...,0,0,0,0,0,0,0,0,0,0
4,https://www.rumah123.com/properti/bekasi/hos10...,4.500000e+09,"rumah hoek di cluster maple summarecon bekasi,...","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"[' Jogging Track', ' Kolam Renang', 'Taman', '...",rumah,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3440,https://www.rumah123.com/properti/tangerang/ho...,5.880000e+08,terbaru cluster minimalis sudimara dekat stasiun,"Jombang, Tangerang",Jombang,Tangerang,-6.296615,106.704601,"['Masjid', ' Taman', 'Tempat Jemuran', 'Keaman...",rumah,...,0,0,0,0,0,0,0,0,0,0
3441,https://www.rumah123.com/properti/tangerang/ho...,7.850000e+08,rumah modern asri dan nyaman bebas banjir loka...,"Lengkong Kulon, Tangerang",Lengkong Kulon,Tangerang,-6.283454,106.638775,"['Masjid', ' Keamanan', ' Jogging Track', ' Ta...",rumah,...,0,0,0,0,0,0,0,0,0,0
3442,https://www.rumah123.com/properti/tangerang/ho...,7.550000e+08,rumah mewah murah 2 lantai gratis biaya biaya ...,"Lengkong Kulon, Tangerang",Lengkong Kulon,Tangerang,-6.283454,106.638775,"[' Keamanan', ' Taman', 'Jogging Track', 'Temp...",rumah,...,0,0,0,0,0,0,0,0,0,0
3443,https://www.rumah123.com/properti/tangerang/ho...,8.000000e+08,rumah 2 lantai dekat perkantoran bsd city aeon...,"BSD Provance Parkland, Tangerang",BSD Provance Parkland,Tangerang,-6.288237,106.665859,"['Tempat Jemuran', 'Keamanan', 'Keamanan 24 ja...",rumah,...,0,0,0,0,0,0,0,0,0,0
3444,https://www.rumah123.com/properti/tangerang/ho...,6.550000e+08,"rumah 2 lantai harga 1 lantai di pamulang, fre...","Sudimara, Tangerang",Sudimara,Tangerang,-6.296963,106.710635,"['Kulkas', 'Masjid', ' Taman', 'Lapangan Bola'...",rumah,...,0,0,0,0,0,0,0,0,0,0

# Selecting features

In [ ]:
df.columns

Index(['url', 'price_in_rp', 'title', 'address', 'district', 'city', 'lat',
       'long', 'facilities', 'property_type', 'ads_id', 'bedrooms',
       'bathrooms', 'land_size_m2', 'building_size_m2', 'carports',
       'certificate', 'electricity', 'maid_bedrooms', 'maid_bathrooms',
       'floors', 'building_age', 'year_built', 'property_condition',
       'building_orientation', 'garages', 'furnishing', 'electricity_num',
       'fac_tempat_jemuran', 'fac_jalur_telepon', 'fac_jogging_track',
       'fac_kolam_renang', 'fac_masjid', 'fac_keamanan', 'fac_cctv',
       'fac_kitchen_set', 'fac_one_gate_system', 'fac_akses_parkir',
       'fac_playground', 'fac_wastafel', 'fac_ac', 'fac_lapangan_basket',
       'fac_tempat_gym', 'fac_kolam_ikan', 'fac_lapangan_voli',
       'fac_lapangan_tenis', 'fac_lapangan_bola', 'fac_mesin_cuci',
       'fac_lapangan_bulu_tangkis', 'fac_kulkas', 'fac_garden',
       'fac_water_heater', 'fac_canopy', 'fac_smart_home', 'fac_backyard_luas',
       'fac_garasi', 'fac_balkon', 'fac_basement', 'fac_gudang',
       'fac_clubhouse', 'fac_service_area', 'fac_plumbing_system'],
      dtype='object')

In [ ]:
# Get the number of null values in each column
null_counts = df.isnull().sum()

# Print the column names and their corresponding number of null values
for column, null_count in null_counts.items():
    print(f"Column: {column}, Null values: {null_count}")

Column: url, Null values: 0
Column: price_in_rp, Null values: 0
Column: title, Null values: 0
Column: address, Null values: 0
Column: district, Null values: 0
Column: city, Null values: 0
Column: lat, Null values: 0
Column: long, Null values: 0
Column: facilities, Null values: 0
Column: property_type, Null values: 1
Column: ads_id, Null values: 4
Column: bedrooms, Null values: 32
Column: bathrooms, Null values: 28
Column: land_size_m2, Null values: 2
Column: building_size_m2, Null values: 2
Column: carports, Null values: 0
Column: certificate, Null values: 140
Column: electricity, Null values: 0
Column: maid_bedrooms, Null values: 0
Column: maid_bathrooms, Null values: 0
Column: floors, Null values: 6
Column: building_age, Null values: 1417
Column: year_built, Null values: 1417
Column: property_condition, Null values: 242
Column: building_orientation, Null values: 1591
Column: garages, Null values: 0
Column: furnishing, Null values: 372
Column: electricity_num, Null values: 285
Column: fac_tempat_jemuran, Null values: 0
Column: fac_jalur_telepon, Null values: 0
Column: fac_jogging_track, Null values: 0
Column: fac_kolam_renang, Null values: 0
Column: fac_masjid, Null values: 0
Column: fac_keamanan, Null values: 0
Column: fac_cctv, Null values: 0
Column: fac_kitchen_set, Null values: 0
Column: fac_one_gate_system, Null values: 0
Column: fac_akses_parkir, Null values: 0
Column: fac_playground, Null values: 0
Column: fac_wastafel, Null values: 0
Column: fac_ac, Null values: 0
Column: fac_lapangan_basket, Null values: 0
Column: fac_tempat_gym, Null values: 0
Column: fac_kolam_ikan, Null values: 0
Column: fac_lapangan_voli, Null values: 0
Column: fac_lapangan_tenis, Null values: 0
Column: fac_lapangan_bola, Null values: 0
Column: fac_mesin_cuci, Null values: 0
Column: fac_lapangan_bulu_tangkis, Null values: 0
Column: fac_kulkas, Null values: 0
Column: fac_garden, Null values: 0
Column: fac_water_heater, Null values: 0
Column: fac_canopy, Null values: 0
Column: fac_smart_home, Null values: 0
Column: fac_backyard_luas, Null values: 0
Column: fac_garasi, Null values: 0
Column: fac_balkon, Null values: 0
Column: fac_basement, Null values: 0
Column: fac_gudang, Null values: 0
Column: fac_clubhouse, Null values: 0
Column: fac_service_area, Null values: 0
Column: fac_plumbing_system, Null values: 0

# Feature Seleciton

In [ ]:
df = df[['district',
         'city',
         'floors',
         'bedrooms',
         'bathrooms',
         'land_size_m2',
         'building_size_m2',
         'carports',
         'garages',
         'price_in_rp']]

In [ ]:
df['tempat_mobil'] = df['carports'] + df['garages']

<ipython-input-15-4a693f3c191b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tempat_mobil'] = df['carports'] + df['garages']

In [ ]:
df.drop(columns=['carports','garages'], inplace=True)

<ipython-input-16-c833548ee078>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['carports','garages'], inplace=True)

In [ ]:
df

,district,city,floors,bedrooms,bathrooms,land_size_m2,building_size_m2,price_in_rp,tempat_mobil
0,Summarecon Bekasi,Bekasi,2.0,4.0,4.0,239.0,272.0,2.990000e+09,0
1,Summarecon Bekasi,Bekasi,2.0,3.0,2.0,55.0,69.0,1.270000e+09,1
2,Summarecon Bekasi,Bekasi,2.0,3.0,3.0,119.0,131.0,1.950000e+09,2
3,Summarecon Bekasi,Bekasi,2.0,3.0,3.0,180.0,174.0,3.300000e+09,2
4,Summarecon Bekasi,Bekasi,2.0,4.0,3.0,328.0,196.0,4.500000e+09,3
...,...,...,...,...,...,...,...,...,...
3440,Jombang,Tangerang,1.0,2.0,1.0,72.0,36.0,5.880000e+08,2
3441,Lengkong Kulon,Tangerang,2.0,3.0,2.0,85.0,60.0,7.850000e+08,1
3442,Lengkong Kulon,Tangerang,2.0,3.0,2.0,78.0,60.0,7.550000e+08,1
3443,BSD Provance Parkland,Tangerang,2.0,3.0,2.0,60.0,65.0,8.000000e+08,2
3444,Sudimara,Tangerang,2.0,3.0,2.0,64.0,60.0,6.550000e+08,3

# Encoding

## Encoding District

Ini encoding berdasarkan median harga dari district tersebut

In [ ]:
# Step 1: Calculate the median of "price_in_rp" for each district
district_medians = df.groupby('district')['price_in_rp'].median()

# Step 2: Sort the categories by their median "price_in_rp" in descending order
sorted_categories_district = district_medians.sort_values(ascending=False).index

# Step 3: Create a dictionary for encoding based on sorted order
encoding_district_dict = {district: idx for idx, district in enumerate(sorted_categories_district, start=1)}

# Print the encoding dictionary
print("Encoding Dictionary:", encoding_district_dict)

# Create a folder named "encoding" if it doesn't exist
encoding_folder = 'encoding'
if not os.path.exists(encoding_folder):
    os.makedirs(encoding_folder)

# Export the encoding to a JSON file in the "encoding" folder
json_file_path = os.path.join(encoding_folder, 'encoding_district_dict.json')
with open(json_file_path, 'w') as json_file:
    json.dump(encoding_district_dict, json_file, indent=4)

print(f"Dictionary has been exported to {json_file_path}")

# Step 4: Encode the "district" column using the encoding dictionary
df['district'] = df['district'].map(encoding_district_dict)

df

Encoding Dictionary: {'patra kuningan': 1, 'Slipi': 2, 'Simprug': 3, 'Menteng': 4, 'Cikini': 5, 'Senopati': 6, 'Setiabudi': 7, 'BSD Bukit Golf': 8, 'Antasari': 9, 'Pantai Mutiara': 10, 'Senayan': 11, 'Tebet': 12, 'Cipete': 13, 'Bendungan Hilir': 14, 'Kebayoran Baru': 15, 'Petojo': 16, 'Ampera': 17, 'Cihuni': 18, 'Intercon': 19, 'Pondok Indah': 20, 'Gatot Subroto': 21, 'Jati Padang': 22, 'Kelapa Gading': 23, 'Kemang': 24, 'Cilendek Barat': 25, 'BSD De Park': 26, 'BSD Telaga Golf': 27, 'Pancoran': 28, 'Gading Serpong Pondok Hijau Golf': 29, 'Kebayoran Lama': 30, 'Mampang Prapatan': 31, 'Tanjung Barat': 32, 'Mangga Besar': 33, 'Bangka': 34, 'Pantai Indah Kapuk': 35, 'Permata Hijau': 36, 'Tanah Kusir': 37, 'Pluit': 38, 'BSD Giri Loka': 39, 'Muara Karang': 40, 'Tomang': 41, 'BSD Anggrek Loka': 42, 'Radio Dalam': 43, 'Duren Tiga': 44, 'Cisarua': 45, 'Kota Bambu Utara': 46, 'Sutera Onix Alam Sutera': 47, 'Green Ville': 48, 'Kayu Putih': 49, 'BSD Green Cove': 50, 'Pejaten': 51, 'Menteng Atas': 52, 'Sunrise Garden': 53, 'Kreo': 54, 'Baranangsiang': 55, 'Permata Buana': 56, 'Gandaria': 57, 'Puri Indah': 58, 'Lebak Bulus': 59, 'Cilandak': 60, 'Gading Serpong IL Lago': 61, 'Citra Garden': 62, 'Puri Media': 63, 'BSD Taman Giri Loka': 64, 'Kedoya Utara': 65, 'Cireundeu': 66, 'Taman Grisenda': 67, 'Cengkareng': 68, 'Alam Sutera': 69, 'BSD Puspita Loka': 70, 'Megamendung': 71, 'Fatmawati': 72, 'BSD The Icon': 73, 'Kalibata': 74, 'Pulomas': 75, 'BSD Duta Bintaro': 76, 'Bintaro': 77, 'Taman Kencana': 78, 'BSD Foresta': 79, 'Ragunan': 80, 'Grogol': 81, 'Ciluar': 82, 'Cempaka Putih': 83, 'Green garden': 84, 'Sektor 3A-Bintaro': 85, 'Pengadegan': 86, 'Cipanas': 87, 'Metland Puri': 88, 'BSD Avani': 89, 'Kresek': 90, 'Gading Serpong The Spring': 91, 'Gading Serpong Andalucia': 92, 'Bantar Gebang': 93, 'Caman': 94, 'Gadog': 95, 'Puri Mansion': 96, 'BSD Sevilla': 97, 'Kebagusan': 98, 'Daan Mogot': 99, 'Gading Serpong L Agricola': 100, 'Tegal Gundi': 101, 'BSD Eminent': 102, 'Sutera Sitara Alam Sutera': 103, 'BSD Delatinos': 104, 'Taman Meruya': 105, 'Joglo': 106, 'Pondok Kelapa': 107, 'Green Lake City': 108, 'Pasar Minggu': 109, 'BSD City': 110, 'Jelambar': 111, 'BSD': 112, 'Gading Serpong': 113, 'Sentul City': 114, 'Sunter': 115, 'Pekayon': 116, 'BSD Griya Loka': 117, 'BSD Kencana Loka': 118, 'Rempoa': 119, 'Gading Serpong Scientia Garden': 120, 'Kalideres': 121, 'Cilendek Timur': 122, 'Banjar Wijaya': 123, 'BSD The Green': 124, 'Duren Sawit': 125, 'Jagakarsa': 126, 'Cawang': 127, 'Pangkalan Jati': 128, 'Rawamangun': 129, 'Kembangan': 130, 'Pagedangan': 131, 'Pedurenan': 132, 'Taman Ratu': 133, 'Pondok Betung': 134, 'Ciparigi': 135, 'Summarecon Bekasi': 136, 'Kembangan Selatan': 137, 'BSD Residence One': 138, 'Sepatan': 139, 'Meruya': 140, 'Pondokmelati': 141, 'Cibodas': 142, 'Legenda Wisata': 143, 'BSD Green Wich': 144, 'Cakung': 145, 'Karang Tengah': 146, 'TB Simatupang': 147, 'Duri Kosambi': 148, 'Katulampa': 149, 'Tegallega': 150, 'Bogor Nirwana Residence': 151, 'Mulyaharja': 152, 'Pasar Rebo': 153, 'BSD Nusaloka': 154, 'Ciawi': 155, 'Grand Wisata': 156, 'BSD Graha Raya': 157, 'Ciganjur': 158, 'Pondok Gede': 159, 'Pabaton': 160, 'Galaxy': 161, 'Kukusan': 162, 'Angke': 163, 'Kemang Pratama': 164, 'Rangga Mekar': 165, 'Cipadu': 166, 'Dramaga': 167, 'Benda': 168, 'Cinere': 169, 'Tangerang Kota': 170, 'Pesanggrahan': 171, 'Jatiwaringin': 172, 'Jaka Sampurna': 173, 'Kota Wisata': 174, 'Ciledug': 175, 'Pasar Kemis': 176, 'Gunung Putri': 177, 'Cimangu': 178, 'Modernland': 179, 'Tanjung Duren': 180, 'Cipinang': 181, 'Jaka Setia': 182, 'Jatinegara': 183, 'Kramat Jati': 184, 'Larangan': 185, 'Margonda': 186, 'Raffles Hills': 187, 'Gading Serpong Samara Village': 188, 'Pinang': 189, 'Duri Kepa': 190, 'Limo': 191, 'Graha Raya': 192, 'Sukaraja': 193, 'Rancamaya': 194, 'Tanah Tinggi': 195, 'Metro permata': 196, 'Bogor Barat': 197, 'Cikokol': 198, 'Tanah Sareal': 199, 'Tajur': 200, 'Cikupa': 201, 'Beji': 202, 'Kranji': 203, 'Bojong Indah': 204, 'Citeureup': 205, 'Citaringgul': 206, 'Pasir Kuda': 207, 'Leuwinanggung': 208, 'Cijeruk': 209, 'Limusnunggal': 210, 'Sentul': 211, 'Cibuluh': 212, 'Pondok Cabe': 213, 'Kedungwaringin': 214, 'Kedungbadak': 215, 'Sukamaju': 216, 'Cilendek': 217, 'Pasirlaja': 218, 'Bantar Jati': 219, 'Harapan Mulya': 220, 'Harjamukti': 221, 'Semplak': 222, 'Sukmajaya': 223, 'Metro Permata': 224, 'Tanah Baru': 225, 'Margahayu': 226, 'Pondok Bambu': 227, 'Jelupang': 228, 'Harapan Indah': 229, 'Duta Harapan': 230, 'Medan Satria': 231, 'Cipondoh': 232, 'Parigi': 233, 'Lippo Karawaci': 234, 'Bitung': 235, 'Cibubur': 236, 'Jatirangga': 237, 'Gandul': 238, 'Jatimakmur': 239, 'Rangkapanjaya': 240, 'Jatisampurna': 241, 'Palmerah': 242, 'Jatiwarna': 243, 'Serua': 244, 'Sindang Barang': 245, 'Jati Cempaka': 246, 'Duta Garden': 247, 'Taman Palem': 248, 'Bekasi': 249, 'Bukit Sentul': 250, 'Jatiraden': 251, 'Sindang Jaya': 252, 'Jatibening': 253, 'Cikunir': 254, 'Batutulis': 255, 'Lubang Buaya': 256, 'Tapos': 257, 'Cisauk': 258, 'Rawalumbu': 259, 'Ciater': 260, 'Bintara': 261, 'Jatiranggon': 262, 'Kelapa Dua': 263, 'Jatimelati': 264, 'Harapan Jaya': 265, 'Bekasi Barat': 266, 'Perwira': 267, 'Poris': 268, 'Harapan Baru': 269, 'Jatikramat': 270, 'Sukatani': 271, 'Karawaci': 272, 'Jati Mekar': 273, 'Cimanggis': 274, 'Kebon Jeruk': 275, 'Batu Ceper': 276, 'Ciracas': 277, 'Tirtajaya': 278, 'Puncak': 279, 'Sawangan': 280, 'Rawakalong': 281, 'Pengasinan': 282, 'Gunung Sindur': 283, 'Bojong Sari': 284, 'Bojongsari': 285, 'Kayuringin Jaya': 286, 'Cikupa Citra Raya': 287, 'Tambora': 288, 'Krukut': 289, 'Jatake': 290, 'Pulo Gadung': 291, 'Ciangsana': 292, 'Curug': 293, 'Ciapus': 294, 'Bekasi Utara': 295, 'BSD Provance Parkland': 296, 'Pos Pengumben': 297, 'Kedung Halang': 298, 'Pancoran Mas': 299, 'Jati Asih': 300, 'Cimahpar': 301, 'Ciomas': 302, 'Tarumajaya': 303, 'Cilodong': 304, 'Cimone': 305, 'Lengkong Kulon': 306, 'Pejuang': 307, 'Bekasi Timur': 308, 'Bekasi Kota': 309, 'Matraman': 310, 'Ciampea': 311, 'Jati Luhur': 312, 'Cinangka': 313, 'Koja': 314, 'Babakan Madang': 315, 'Cimuning': 316, 'Komsen': 317, 'Jatimurni': 318, 'Jababeka': 319, 'Pasirmulya': 320, 'Cipayung': 321, 'Babakan': 322, 'Mustikajaya': 323, 'Cibinong': 324, 'Parung': 325, 'Tambun Selatan': 326, 'Depok II': 327, 'Bakti Jaya': 328, 'Sudimara': 329, 'Cikeas': 330, 'Duren Jaya': 331, 'Pondok Benda': 332, 'Cibitung': 333, 'Sempur': 334, 'Mustikasari': 335, 'Kaliabang': 336, 'Cikarang': 337, 'Cileungsi': 338, 'Pamoyanan': 339, 'Jombang': 340, 'Balaraja': 341, 'Panongan': 342, 'Bojong Kulur': 343, 'Narogong': 344, 'Pasar Baru': 345, 'Pinang Ranti': 346, 'Rumpin': 347, 'Tigaraksa': 348, 'Tamansari': 349, 'Ciseeng': 350, 'Cilangkap': 351, 'Tanjung Priok': 352, 'Golden City': 353, 'Parung Panjang': 354, 'Jati Sari': 355, 'Cisalak': 356, 'Kemayoran': 357, 'Sumur Batu': 358, 'Karang Satria': 359, 'Pondok Ungu': 360, 'Tajur Halang': 361, 'Senen': 362, 'Bojong': 363, 'Utan Kayu': 364, 'Satriajaya': 365, 'Cikarang Selatan': 366, 'Bojong Gede': 367, 'Cilebut': 368, 'Citayam': 369, 'Babelan': 370, 'Setu': 371, 'Tambun Utara': 372, 'Jonggol': 373, 'Tenjo': 374, 'Kebalen': 375, 'Serang Baru': 376}
Dictionary has been exported to encoding/encoding_district_dict.json

<ipython-input-18-ef7aa796cb42>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['district'] = df['district'].map(encoding_district_dict)

,district,city,floors,bedrooms,bathrooms,land_size_m2,building_size_m2,price_in_rp,tempat_mobil
0,136,Bekasi,2.0,4.0,4.0,239.0,272.0,2.990000e+09,0
1,136,Bekasi,2.0,3.0,2.0,55.0,69.0,1.270000e+09,1
2,136,Bekasi,2.0,3.0,3.0,119.0,131.0,1.950000e+09,2
3,136,Bekasi,2.0,3.0,3.0,180.0,174.0,3.300000e+09,2
4,136,Bekasi,2.0,4.0,3.0,328.0,196.0,4.500000e+09,3
...,...,...,...,...,...,...,...,...,...
3440,340,Tangerang,1.0,2.0,1.0,72.0,36.0,5.880000e+08,2
3441,306,Tangerang,2.0,3.0,2.0,85.0,60.0,7.850000e+08,1
3442,306,Tangerang,2.0,3.0,2.0,78.0,60.0,7.550000e+08,1
3443,296,Tangerang,2.0,3.0,2.0,60.0,65.0,8.000000e+08,2
3444,329,Tangerang,2.0,3.0,2.0,64.0,60.0,6.550000e+08,3

# Encoding City

Ini encoding berdasarkan median harga dari city tersebut

In [ ]:
# Step 1: Calculate the median of "price_in_rp" for each city
city_medians = df.groupby('city')['price_in_rp'].median()

# Step 2: Sort the categories by their median "price_in_rp" in descending order
sorted_categories_city = city_medians.sort_values(ascending=False).index

# Step 3: Create a dictionary for encoding based on sorted order
encoding_city_dict = {city: idx for idx, city in enumerate(sorted_categories_city, start=1)}

# Print the encoding dictionary
print("Encoding Dictionary:", encoding_city_dict)

# Export the encoding to a JSON file in the "encoding" folder
json_file_path = os.path.join(encoding_folder, 'encoding_city_dict.json')
with open(json_file_path, 'w') as json_file:
    json.dump(encoding_city_dict, json_file, indent=4)

print(f"Dictionary has been exported to {json_file_path}")

# Step 4: Encode the "city" column using the encoding dictionary
df['city'] = df['city'].map(encoding_city_dict)

df

Encoding Dictionary: {' Jakarta Utara': 1, ' Jakarta Selatan': 2, ' Jakarta Pusat': 3, ' Jakarta Barat': 4, ' Tangerang': 5, ' Jakarta Timur': 6, ' Bogor': 7, ' Depok': 8, ' Bekasi': 9}
Dictionary has been exported to encoding/encoding_city_dict.json

<ipython-input-19-82028b7af9b7>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = df['city'].map(encoding_city_dict)

,district,city,floors,bedrooms,bathrooms,land_size_m2,building_size_m2,price_in_rp,tempat_mobil
0,136,9,2.0,4.0,4.0,239.0,272.0,2.990000e+09,0
1,136,9,2.0,3.0,2.0,55.0,69.0,1.270000e+09,1
2,136,9,2.0,3.0,3.0,119.0,131.0,1.950000e+09,2
3,136,9,2.0,3.0,3.0,180.0,174.0,3.300000e+09,2
4,136,9,2.0,4.0,3.0,328.0,196.0,4.500000e+09,3
...,...,...,...,...,...,...,...,...,...
3440,340,5,1.0,2.0,1.0,72.0,36.0,5.880000e+08,2
3441,306,5,2.0,3.0,2.0,85.0,60.0,7.850000e+08,1
3442,306,5,2.0,3.0,2.0,78.0,60.0,7.550000e+08,1
3443,296,5,2.0,3.0,2.0,60.0,65.0,8.000000e+08,2
3444,329,5,2.0,3.0,2.0,64.0,60.0,6.550000e+08,3

# Normalization

Using the max-min normalization

In [ ]:
# Compute maximum and minimum values for each column
max_values = df.max()
min_values = df.min()

# Construct dictionary with maximum and minimum values for each column
result_dict = {}
for column in df.columns:
  if(column == "price_in_rp"):
    continue
  result_dict[f"{column}_max"] = max_values[column]
  result_dict[f"{column}_min"] = min_values[column]

# Specify the file path where you want to save the JSON
json_file_path = os.path.join(encoding_folder, 'max_min_values.json')

# Write the dictionary to a JSON file
with open(json_file_path, 'w') as json_file:
  json.dump(result_dict, json_file, indent=4)

print(f"Dictionary has been exported to {json_file_path}")

Dictionary has been exported to encoding/max_min_values.json

In [ ]:
# Function to normalize a column using min-max scaling
def min_max_normalize(column):
    min_val = column.min()
    max_val = column.max()
    normalized_column = (column - min_val) / (max_val - min_val)
    return normalized_column

# Apply normalization to all columns except "price_in_rp"
normalized_columns = df.drop(columns=['price_in_rp']).apply(min_max_normalize)

# Add the "price_in_rp" column back to the normalized DataFrame
df = pd.concat([normalized_columns, df['price_in_rp']], axis=1)

df

,district,city,floors,bedrooms,bathrooms,land_size_m2,building_size_m2,tempat_mobil,price_in_rp
0,0.360000,1.0,0.25,0.030612,0.030612,0.028418,0.042461,0.00,2.990000e+09
1,0.360000,1.0,0.25,0.020408,0.010204,0.005383,0.008526,0.02,1.270000e+09
2,0.360000,1.0,0.25,0.020408,0.020408,0.013395,0.018890,0.04,1.950000e+09
3,0.360000,1.0,0.25,0.020408,0.020408,0.021032,0.026078,0.04,3.300000e+09
4,0.360000,1.0,0.25,0.030612,0.020408,0.039559,0.029756,0.06,4.500000e+09
...,...,...,...,...,...,...,...,...,...
3440,0.904000,0.5,0.00,0.010204,0.000000,0.007511,0.003009,0.04,5.880000e+08
3441,0.813333,0.5,0.25,0.020408,0.010204,0.009139,0.007021,0.02,7.850000e+08
3442,0.813333,0.5,0.25,0.020408,0.010204,0.008262,0.007021,0.02,7.550000e+08
3443,0.786667,0.5,0.25,0.020408,0.010204,0.006009,0.007857,0.04,8.000000e+08
3444,0.874667,0.5,0.25,0.020408,0.010204,0.006510,0.007021,0.06,6.550000e+08

# Null Values

Assumption : Dropping null values

In [ ]:
df = df.dropna()

# Data Split

In [ ]:
# Separate features and target variable
X = df.drop(columns=['price_in_rp'])
y = df['price_in_rp']

# Split the dataset into training, dev, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_dev, X_test, y_dev, y_test = train_test_split(X_temp, y_temp, test_size=0.333, random_state=42)

# Create a folder named "dataset" if it doesn't exist
dataset_folder = 'dataset'
if not os.path.exists(dataset_folder):
    os.makedirs(dataset_folder)

# Export sets to CSV files in the "dataset" folder
X_train.to_csv(os.path.join(dataset_folder, 'train_set.csv'), index=False)
y_train.to_csv(os.path.join(dataset_folder, 'train_target.csv'), index=False)
X_dev.to_csv(os.path.join(dataset_folder, 'dev_set.csv'), index=False)
y_dev.to_csv(os.path.join(dataset_folder, 'dev_target.csv'), index=False)
X_test.to_csv(os.path.join(dataset_folder, 'test_set.csv'), index=False)
y_test.to_csv(os.path.join(dataset_folder, 'test_target.csv'), index=False)

print("Datasets have been exported to the 'dataset' folder.")

Datasets have been exported to the 'dataset' folder.

# Machine Learning

In [ ]:
from sklearn.metrics import r2_score

# Define the input shape
input_shape = X_train.shape[1:]

# Define the model architecture with increased complexity
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=input_shape),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

# Compile the model with a lower learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=0.9)  # Adjust learning rate
model.compile(optimizer=optimizer, loss='mse', metrics=['mse'])

# Train the model with more epochs
history = model.fit(X_train, y_train, epochs=100, verbose=1)

# Calculate R-squared (R2) score
y_train_pred = model.predict(X_train)
train_r2_score = r2_score(y_train, y_train_pred)

print("Training R2 score:", train_r2_score)

Epoch 1/100
75/75 [==============================] - 5s 9ms/step - loss: 87156008545710768128.0000 - mse: 87156008545710768128.0000
Epoch 2/100
75/75 [==============================] - 0s 4ms/step - loss: 50955256704255655936.0000 - mse: 50955256704255655936.0000
Epoch 3/100
75/75 [==============================] - 0s 5ms/step - loss: 43522654857513140224.0000 - mse: 43522654857513140224.0000
Epoch 4/100
75/75 [==============================] - 0s 6ms/step - loss: 40301930213059592192.0000 - mse: 40301930213059592192.0000
Epoch 5/100
75/75 [==============================] - 1s 7ms/step - loss: 38112076884483244032.0000 - mse: 38112076884483244032.0000
Epoch 6/100
75/75 [==============================] - 0s 5ms/step - loss: 36033830583195926528.0000 - mse: 36033830583195926528.0000
Epoch 7/100
75/75 [==============================] - 0s 5ms/step - loss: 34271069352289632256.0000 - mse: 34271069352289632256.0000
Epoch 8/100
75/75 [==============================] - 0s 5ms/step - loss: 32378295269445337088.0000 - mse: 32378295269445337088.0000
Epoch 9/100
75/75 [==============================] - 0s 5ms/step - loss: 31668870575994961920.0000 - mse: 31668870575994961920.0000
Epoch 10/100
75/75 [==============================] - 0s 5ms/step - loss: 30796280556005883904.0000 - mse: 30796280556005883904.0000
Epoch 11/100
75/75 [==============================] - 0s 3ms/step - loss: 32110927026919047168.0000 - mse: 32110927026919047168.0000
Epoch 12/100
75/75 [==============================] - 0s 4ms/step - loss: 29227937170146197504.0000 - mse: 29227937170146197504.0000
Epoch 13/100
75/75 [==============================] - 0s 4ms/step - loss: 31595823421492035584.0000 - mse: 31595823421492035584.0000
Epoch 14/100
75/75 [==============================] - 0s 5ms/step - loss: 30739693090570764288.0000 - mse: 30739693090570764288.0000
Epoch 15/100
75/75 [==============================] - 0s 2ms/step - loss: 30408992978284576768.0000 - mse: 30408992978284576768.0000
Epoch 16/100
75/75 [==============================] - 0s 2ms/step - loss: 33291481457755160576.0000 - mse: 33291481457755160576.0000
Epoch 17/100
75/75 [==============================] - 0s 2ms/step - loss: 30134185440084754432.0000 - mse: 30134185440084754432.0000
Epoch 18/100
75/75 [==============================] - 0s 2ms/step - loss: 29931066060015927296.0000 - mse: 29931066060015927296.0000
Epoch 19/100
75/75 [==============================] - 0s 2ms/step - loss: 29282963329069875200.0000 - mse: 29282963329069875200.0000
Epoch 20/100
75/75 [==============================] - 0s 2ms/step - loss: 31230822944465747968.0000 - mse: 31230822944465747968.0000
Epoch 21/100
75/75 [==============================] - 0s 2ms/step - loss: 28172746856085848064.0000 - mse: 28172746856085848064.0000
Epoch 22/100
75/75 [==============================] - 0s 2ms/step - loss: 27781718739806846976.0000 - mse: 27781718739806846976.0000
Epoch 23/100
75/75 [==============================] - 0s 2ms/step - loss: 28822808916752596992.0000 - mse: 28822808916752596992.0000
Epoch 24/100
75/75 [==============================] - 0s 2ms/step - loss: 30796643394843049984.0000 - mse: 30796643394843049984.0000
Epoch 25/100
75/75 [==============================] - 0s 2ms/step - loss: 30145259721199714304.0000 - mse: 30145259721199714304.0000
Epoch 26/100
75/75 [==============================] - 0s 2ms/step - loss: 28281796419328671744.0000 - mse: 28281796419328671744.0000
Epoch 27/100
75/75 [==============================] - 0s 2ms/step - loss: 28236305225241067520.0000 - mse: 28236305225241067520.0000
Epoch 28/100
75/75 [==============================] - 0s 2ms/step - loss: 26862388480521011200.0000 - mse: 26862388480521011200.0000
Epoch 29/100
75/75 [==============================] - 0s 2ms/step - loss: 26994633341063397376.0000 - mse: 26994633341063397376.0000
Epoch 30/100
75/75 [==============================] - 0s 2ms/step - loss: 30845897117720903680.0000 - mse: 30845897117720903680.0000
Epoch 31/100
75/75 [==============================] - 0s 2ms/step - loss: 27236926121406627840.0000 - mse: 27236926121406627840.0000
Epoch 32/100
75/75 [==============================] - 0s 2ms/step - loss: 27615149325268549632.0000 - mse: 27615149325268549632.0000
Epoch 33/100
75/75 [==============================] - 0s 2ms/step - loss: 27242359907871096832.0000 - mse: 27242359907871096832.0000
Epoch 34/100
75/75 [==============================] - 0s 2ms/step - loss: 26288817244775383040.0000 - mse: 26288817244775383040.0000
Epoch 35/100
75/75 [==============================] - 0s 2ms/step - loss: 27968479585877622784.0000 - mse: 27968479585877622784.0000
Epoch 36/100
75/75 [==============================] - 0s 2ms/step - loss: 27759552585390882816.0000 - mse: 27759552585390882816.0000
Epoch 37/100
75/75 [==============================] - 0s 2ms/step - loss: 25733911318422880256.0000 - mse: 25733911318422880256.0000
Epoch 38/100
75/75 [==============================] - 0s 2ms/step - loss: 27289196904191098880.0000 - mse: 27289196904191098880.0000
Epoch 39/100
75/75 [==============================] - 0s 2ms/step - loss: 28950545779621101568.0000 - mse: 28950545779621101568.0000
Epoch 40/100
75/75 [==============================] - 0s 2ms/step - loss: 27000346403481321472.0000 - mse: 27000346403481321472.0000
Epoch 41/100
75/75 [==============================] - 0s 2ms/step - loss: 28127488758463332352.0000 - mse: 28127488758463332352.0000
Epoch 42/100
75/75 [==============================] - 0s 2ms/step - loss: 25208058887322730496.0000 - mse: 25208058887322730496.0000
Epoch 43/100
75/75 [==============================] - 0s 2ms/step - loss: 30857076951952130048.0000 - mse: 30857076951952130048.0000
Epoch 44/100
75/75 [==============================] - 0s 2ms/step - loss: 28452985981726883840.0000 - mse: 28452985981726883840.0000
Epoch 45/100
75/75 [==============================] - 0s 2ms/step - loss: 26110744739587293184.0000 - mse: 26110744739587293184.0000
Epoch 46/100
75/75 [==============================] - 0s 2ms/step - loss: 28456145978145112064.0000 - mse: 28456145978145112064.0000
Epoch 47/100
75/75 [==============================] - 0s 2ms/step - loss: 27509193787746287616.0000 - mse: 27509193787746287616.0000
Epoch 48/100
75/75 [==============================] - 0s 2ms/step - loss: 31050302926394228736.0000 - mse: 31050302926394228736.0000
Epoch 49/100
75/75 [==============================] - 0s 2ms/step - loss: 25889558184450850816.0000 - mse: 25889558184450850816.0000
Epoch 50/100
75/75 [==============================] - 0s 2ms/step - loss: 24923714185263579136.0000 - mse: 24923714185263579136.0000
Epoch 51/100
75/75 [==============================] - 0s 2ms/step - loss: 25955328771001155584.0000 - mse: 25955328771001155584.0000
Epoch 52/100
75/75 [==============================] - 0s 2ms/step - loss: 27472232604866969600.0000 - mse: 27472232604866969600.0000
Epoch 53/100
75/75 [==============================] - 0s 2ms/step - loss: 24999204454603423744.0000 - mse: 24999204454603423744.0000
Epoch 54/100
75/75 [==============================] - 0s 2ms/step - loss: 24737652628588068864.0000 - mse: 24737652628588068864.0000
Epoch 55/100
75/75 [==============================] - 0s 2ms/step - loss: 27116195346630311936.0000 - mse: 27116195346630311936.0000
Epoch 56/100
75/75 [==============================] - 0s 2ms/step - loss: 27224382892756959232.0000 - mse: 27224382892756959232.0000
Epoch 57/100
75/75 [==============================] - 0s 2ms/step - loss: 26019997646900428800.0000 - mse: 26019997646900428800.0000
Epoch 58/100
75/75 [==============================] - 0s 2ms/step - loss: 25442646290178506752.0000 - mse: 25442646290178506752.0000
Epoch 59/100
75/75 [==============================] - 0s 2ms/step - loss: 25708926016193298432.0000 - mse: 25708926016193298432.0000
Epoch 60/100
75/75 [==============================] - 0s 2ms/step - loss: 24400329058256158720.0000 - mse: 24400329058256158720.0000
Epoch 61/100
75/75 [==============================] - 0s 2ms/step - loss: 25821395060598505472.0000 - mse: 25821395060598505472.0000
Epoch 62/100
75/75 [==============================] - 0s 2ms/step - loss: 26074419074428829696.0000 - mse: 26074419074428829696.0000
Epoch 63/100
75/75 [==============================] - 0s 3ms/step - loss: 25614702267739406336.0000 - mse: 25614702267739406336.0000
Epoch 64/100
75/75 [==============================] - 0s 3ms/step - loss: 25034615326087577600.0000 - mse: 25034615326087577600.0000
Epoch 65/100
75/75 [==============================] - 0s 3ms/step - loss: 25228824263924908032.0000 - mse: 25228824263924908032.0000
Epoch 66/100
75/75 [==============================] - 0s 3ms/step - loss: 24537796599030480896.0000 - mse: 24537796599030480896.0000
Epoch 67/100
75/75 [==============================] - 0s 3ms/step - loss: 24627076943205892096.0000 - mse: 24627076943205892096.0000
Epoch 68/100
75/75 [==============================] - 0s 3ms/step - loss: 22696849096273035264.0000 - mse: 22696849096273035264.0000
Epoch 69/100
75/75 [==============================] - 0s 3ms/step - loss: 24610038911021875200.0000 - mse: 24610038911021875200.0000
Epoch 70/100
75/75 [==============================] - 0s 3ms/step - loss: 25439196022690545664.0000 - mse: 25439196022690545664.0000
Epoch 71/100
75/75 [==============================] - 0s 3ms/step - loss: 23216416718908817408.0000 - mse: 23216416718908817408.0000
Epoch 72/100
75/75 [==============================] - 0s 3ms/step - loss: 23571081786634010624.0000 - mse: 23571081786634010624.0000
Epoch 73/100
75/75 [==============================] - 0s 3ms/step - loss: 24916334263217946624.0000 - mse: 24916334263217946624.0000
Epoch 74/100
75/75 [==============================] - 0s 3ms/step - loss: 24854673651132268544.0000 - mse: 24854673651132268544.0000
Epoch 75/100
75/75 [==============================] - 0s 3ms/step - loss: 22516575368806137856.0000 - mse: 22516575368806137856.0000
Epoch 76/100
75/75 [==============================] - 0s 3ms/step - loss: 25013874138741211136.0000 - mse: 25013874138741211136.0000
Epoch 77/100
75/75 [==============================] - 0s 3ms/step - loss: 23340738498661449728.0000 - mse: 23340738498661449728.0000
Epoch 78/100
75/75 [==============================] - 0s 3ms/step - loss: 25015268319485231104.0000 - mse: 25015268319485231104.0000
Epoch 79/100
75/75 [==============================] - 0s 3ms/step - loss: 22994913504423575552.0000 - mse: 22994913504423575552.0000
Epoch 80/100
75/75 [==============================] - 0s 2ms/step - loss: 24393465906675580928.0000 - mse: 24393465906675580928.0000
Epoch 81/100
75/75 [==============================] - 0s 2ms/step - loss: 22702168533528215552.0000 - mse: 22702168533528215552.0000
Epoch 82/100
75/75 [==============================] - 0s 2ms/step - loss: 22332732626595479552.0000 - mse: 22332732626595479552.0000
Epoch 83/100
75/75 [==============================] - 0s 2ms/step - loss: 22601237764144889856.0000 - mse: 22601237764144889856.0000
Epoch 84/100
75/75 [==============================] - 0s 2ms/step - loss: 21305107069043474432.0000 - mse: 21305107069043474432.0000
Epoch 85/100
75/75 [==============================] - 0s 2ms/step - loss: 22815935001654198272.0000 - mse: 22815935001654198272.0000
Epoch 86/100
75/75 [==============================] - 0s 2ms/step - loss: 25286537629266870272.0000 - mse: 25286537629266870272.0000
Epoch 87/100
75/75 [==============================] - 0s 2ms/step - loss: 21970729418266509312.0000 - mse: 21970729418266509312.0000
Epoch 88/100
75/75 [==============================] - 0s 2ms/step - loss: 24732306803053821952.0000 - mse: 24732306803053821952.0000
Epoch 89/100
75/75 [==============================] - 0s 2ms/step - loss: 23674411690389143552.0000 - mse: 23674411690389143552.0000
Epoch 90/100
75/75 [==============================] - 0s 2ms/step - loss: 23109062602596024320.0000 - mse: 23109062602596024320.0000
Epoch 91/100
75/75 [==============================] - 0s 2ms/step - loss: 22430984985653542912.0000 - mse: 22430984985653542912.0000
Epoch 92/100
75/75 [==============================] - 0s 2ms/step - loss: 23801152395722883072.0000 - mse: 23801152395722883072.0000
Epoch 93/100
75/75 [==============================] - 0s 2ms/step - loss: 22502079407505539072.0000 - mse: 22502079407505539072.0000
Epoch 94/100
75/75 [==============================] - 0s 2ms/step - loss: 22697649540738056192.0000 - mse: 22697649540738056192.0000
Epoch 95/100
75/75 [==============================] - 0s 2ms/step - loss: 22955300299498061824.0000 - mse: 22955300299498061824.0000
Epoch 96/100
75/75 [==============================] - 0s 2ms/step - loss: 22758428344498257920.0000 - mse: 22758428344498257920.0000
Epoch 97/100
75/75 [==============================] - 0s 2ms/step - loss: 22034742985235628032.0000 - mse: 22034742985235628032.0000
Epoch 98/100
75/75 [==============================] - 0s 2ms/step - loss: 22607826037818523648.0000 - mse: 22607826037818523648.0000
Epoch 99/100
75/75 [==============================] - 0s 2ms/step - loss: 22500177252389486592.0000 - mse: 22500177252389486592.0000
Epoch 100/100
75/75 [==============================] - 0s 2ms/step - loss: 21856340626559205376.0000 - mse: 21856340626559205376.0000
75/75 [==============================] - 0s 1ms/step
Training R2 score: 0.7615178162377717